logging:
  log_dir: ~/RynnRcplog/robot_motion
  log_file: robot_motion.log
robot:
  port: /dev/ttyACM0
  inference_rate: 30.0
  timeout_seconds: 30.0
simulation:
  scene_path: {1: "models/lerobot/so101/scene/scene.xml", 
               2: "models/lerobot/so101/scene/scene_grip.xml", 
               3: "models/lerobot/lekiwi/scene/scene.xml"}
  random_init_pose: false
spline:
  boundary_condition: natural # "natural", "periodic", "clamped", "not-a-knot"
plot:
  enable_joint_plotting: false
  enable_interpolator_plotting: false
  show_plots: false
