config_type: rynnrcp_server_config
version: 1
manifest:
  robot_id: so101_follower
  robot_name: SO101 Follower
  capabilities:
    observations: true
    actions: true
    health: true
    resources: true
    data_collection: true
    policy_service: false
integration:
  config: package://rynnrcp_robot_so101/config/robot_integration.yaml
components:
  robot:
    enabled: true
    role: follower
    port: /dev/cu.usbmodem5AE70441561
  front_camera:
    enabled: true
    device_id: 0
  wrist_camera:
    enabled: true
    device_id: 1
