cameras:
  front:
    color_mode: rgb
    fps: 30
    height: 480
    index_or_path: 0
    type: opencv
    width: 640
  wrist:
    color_mode: rgb
    fps: 30
    height: 480
    index_or_path: 1
    type: opencv
    width: 640
logging:
  log_dir: ~/RynnRcplog/RynnMotion
  log_file: RynnMotion.log
plot:
  enable_interpolator_plotting: false
  enable_joint_plotting: false
  show_plots: false
robot:
  baudrate: 1000000
  calibration_dir: ~/.cache/huggingface/lerobot/calibration/robots/so101_follower
  inference_rate: 30.0
  model: sts3215
  port: /dev/ttyACM1
  timeout_seconds: 30.0
  robot_type: so101
simulation:
  camera_frequency: 30
  camera_name: Wrist_camera
  camera_saving_mode: none
  cube_grabber_initial_keyframe: middle
  cube_grabber_mode: Pcontrol
  random_init_joints: false
spline:
  boundary_condition: natural
teleoperate:
  baudrate: 1000000
  calibration_dir: ~/.cache/huggingface/lerobot/calibration/teleoperators/so101_leader
  calibration_dir_2: ~/.cache/huggingface/lerobot/calibration/teleoperators/so101_leader_2
  inference_rate: 30.0
  model: sts3215
  port: /dev/ttyACM0
  port_2: /dev/ttyACM0
  timeout_seconds: 30.0
leader:
  port: /dev/ttyACM0
