# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RobotServerData.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15RobotServerData.proto\x12\x0bRobotServer\"J\n\x05\x41rray\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\r\n\x05shape\x18\x02 \x03(\x05\x12$\n\x05\x64type\x18\x03 \x01(\x0e\x32\x15.RobotServer.DataType\"`\n\x06\x41\x63tion\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\'\n\x0b\x61\x63tion_data\x18\x03 \x01(\x0b\x32\x12.RobotServer.Array\x12\x13\n\x0b\x61\x63tion_rate\x18\x04 \x01(\x05\"7\n\x0bMultiAction\x12(\n\x0b\x61\x63tion_list\x18\x01 \x03(\x0b\x32\x13.RobotServer.Action\"I\n\x05State\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12&\n\nstate_data\x18\x03 \x01(\x0b\x32\x12.RobotServer.Array\"4\n\nMultiState\x12&\n\nstate_list\x18\x01 \x03(\x0b\x32\x12.RobotServer.State\"Y\n\x05Image\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06\x66ormat\x18\x03 \x01(\t\x12&\n\nimage_data\x18\x04 \x01(\x0b\x32\x12.RobotServer.Array\"4\n\nMultiImage\x12&\n\nimage_list\x18\x01 \x03(\x0b\x32\x12.RobotServer.Image\"/\n\x08ReqImage\x12#\n\x06\x63\x61mera\x18\x01 \x03(\x0b\x32\x13.RobotServer.Camera\"-\n\x08ReqState\x12!\n\x05robot\x18\x01 \x03(\x0b\x32\x12.RobotServer.Robot\"0\n\x06\x43\x61mera\x12\x11\n\tcamera_id\x18\x01 \x01(\x05\x12\x13\n\x0b\x63\x61mera_name\x18\x02 \x01(\t\"-\n\x05Robot\x12\x10\n\x08robot_id\x18\x01 \x01(\x05\x12\x12\n\nrobot_name\x18\x02 \x01(\t\"a\n\x11\x46inishActionChunk\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x11\n\terror_msg\x18\x02 \x01(\t\x12\x15\n\rexecute_steps\x18\x03 \x01(\x05\x12\x14\n\x0c\x65xpect_steps\x18\x04 \x01(\x05*h\n\x08\x44\x61taType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\t\n\x05UINT8\x10\x01\x12\x08\n\x04INT8\x10\x02\x12\n\n\x06UINT16\x10\x03\x12\t\n\x05INT16\x10\x04\x12\t\n\x05INT32\x10\x05\x12\x0b\n\x07\x46LOAT32\x10\x06\x12\x0b\n\x07\x46LOAT64\x10\x07\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RobotServerData_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DATATYPE']._serialized_start=835
  _globals['_DATATYPE']._serialized_end=939
  _globals['_ARRAY']._serialized_start=38
  _globals['_ARRAY']._serialized_end=112
  _globals['_ACTION']._serialized_start=114
  _globals['_ACTION']._serialized_end=210
  _globals['_MULTIACTION']._serialized_start=212
  _globals['_MULTIACTION']._serialized_end=267
  _globals['_STATE']._serialized_start=269
  _globals['_STATE']._serialized_end=342
  _globals['_MULTISTATE']._serialized_start=344
  _globals['_MULTISTATE']._serialized_end=396
  _globals['_IMAGE']._serialized_start=398
  _globals['_IMAGE']._serialized_end=487
  _globals['_MULTIIMAGE']._serialized_start=489
  _globals['_MULTIIMAGE']._serialized_end=541
  _globals['_REQIMAGE']._serialized_start=543
  _globals['_REQIMAGE']._serialized_end=590
  _globals['_REQSTATE']._serialized_start=592
  _globals['_REQSTATE']._serialized_end=637
  _globals['_CAMERA']._serialized_start=639
  _globals['_CAMERA']._serialized_end=687
  _globals['_ROBOT']._serialized_start=689
  _globals['_ROBOT']._serialized_end=734
  _globals['_FINISHACTIONCHUNK']._serialized_start=736
  _globals['_FINISHACTIONCHUNK']._serialized_end=833
# @@protoc_insertion_point(module_scope)
