# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TunnelTransportService.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import RobotServerTransportPacket_pb2 as RobotServerTransportPacket__pb2

from RobotServerTransportPacket_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cTunnelTransportService.proto\x12\x0bRobotServer\x1a RobotServerTransportPacket.proto2_\n\x16TunnelTransportService\x12\x45\n\rbiTransDevice\x12\x17.RobotServer.DataPacket\x1a\x17.RobotServer.DataPacket(\x01\x30\x01\x42-\n)com.alibaba.damo.robot.tele.ops.api.innerP\x01P\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'TunnelTransportService_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n)com.alibaba.damo.robot.tele.ops.api.innerP\001'
  _globals['_TUNNELTRANSPORTSERVICE']._serialized_start=79
  _globals['_TUNNELTRANSPORTSERVICE']._serialized_end=174
# @@protoc_insertion_point(module_scope)
