# rcp_core/common/adapter/output_adapter/generic_chunk_output_adapter.py

"""
Generic chunk-mode output adapter.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

This module defines :class:`~rcp_core.common.adapter.output_adapter.generic_chunk_output_adapter.GenericChunkOutputAdapter`,
an output adapter that publishes an entire action chunk as a single message.

It reuses :class:`~rcp_core.common.adapter.output_adapter.generic_step_output_adapter.GenericStepOutputAdapter`
to build per-step messages, then concatenates each step's ``out_field`` data into one
flattened 1-D sequence. The result is returned as a single frame with:

- ``interval`` = ``N / fps`` (where ``N`` is the number of logical frames)
- ``step`` = ``N``

Constraints (same as the step adapter):
- only one output is supported
- only one mapping is supported
- the mapping key must be ``"action"``

For message types that require explicit ``*_length`` fields or other special handling,
a dedicated adapter is recommended over this generic implementation.
"""

from typing import Any, Dict, List, Tuple

from .base_output_adapter import BaseOutputAdapter
from .generic_step_output_adapter import GenericStepOutputAdapter


class GenericChunkOutputAdapter(BaseOutputAdapter):
    """
    Chunk mode:
    - Based on GenericStepOutputAdapter, concatenates all frame out_field into one long array.
    - Inputs and configuration constraints are the same as GenericStepOutputAdapter.
    - Config (outputs) only supports:
        - a single output
        - a single mapping
        - mapping key must be "action"
    - Output:
        frames_msgs: List[List[(protocol, topic, msg, interval, step)]]
        Only 1 frame:
          [
            [(protocol, topic, merged_msg, interval_chunk, step_chunk)]
          ]
        merged_msg.out_field = frame0 + frame1 + ... + frame{N-1} flattened into a 1D array
        interval_chunk = N / fps
        step_chunk = N

    Likewise: for messages with *_length fields, it is recommended to use a dedicated adapter instead of this generic one.
    """

    def __init__(self):
        self._step = GenericStepOutputAdapter()

    def build_frames(
        self,
        action_chunk: Dict[str, Any],
        outputs: List[Dict[str, Any]],
        fps: int,
    ) -> List[List[Tuple[str, str, Any, float, int]]]:
        """Build a single chunk frame by merging per-step frames generated by GenericStepOutputAdapter."""
        step_frames_msgs = self._step.build_frames(action_chunk, outputs, fps)
        if not step_frames_msgs:
            return []

        num_frames = len(step_frames_msgs)

        protocol, topic, first_msg, _, _ = step_frames_msgs[0][0]
        Msg = first_msg.__class__

        out = outputs[0]
        mapping = out["mappings"][0]
        out_field = mapping["out_field"]

        merged_data: List[Any] = []
        for triplets in step_frames_msgs:
            _, _, msg, _, _ = triplets[0]
            vals = getattr(msg, out_field)
            merged_data.extend(list(vals))

        merged_msg = Msg()
        setattr(merged_msg, out_field, merged_data)

        interval_chunk = float(num_frames) / fps if fps > 0 else 0.0
        step_chunk = num_frames

        return [[(protocol, topic, merged_msg, interval_chunk, step_chunk)]]
