# scripts/gen_lcm_msg.py
"""
Generate *.py from .lcm files into common/lcm/lcm_types using lcm-gen.

Usage (from repo root, e.g. RynnRCP/):

    python scripts/gen_lcm_msg.py
"""
from __future__ import annotations

import os
import sys
import shutil
import subprocess
from pathlib import Path


def run(cmd, cwd=None):
    """Execute a shell command and print the command being run."""
    print(f"[CMD] {' '.join(cmd)}  (cwd={cwd or os.getcwd()})")
    subprocess.check_call(cmd, cwd=cwd)


def find_project_root() -> Path:
    """Find and return the project's root directory as a Path object."""
    return Path(__file__).resolve().parent.parent


def basic_checks() -> Path:
    """Perform checks to ensure the environment is correctly set up for LCM code generation."""
    project_root = find_project_root()
    print(f"[INFO] PROJECT_ROOT = {project_root}")

    lcm_types_dir = project_root / "common" / "lcm" / "lcm_types"
    print(f"[INFO] LCM_TYPES_DIR = {lcm_types_dir}")
    if not lcm_types_dir.is_dir():
        print(f"[ERROR] Directory does not exist: {lcm_types_dir}")
        sys.exit(1)

    lcm_files = list(lcm_types_dir.glob("*.lcm"))
    if not lcm_files:
        print(f"[ERROR] No .lcm files found in {lcm_types_dir}")
        sys.exit(1)

    print("[INFO] Found .lcm files:")
    for f in lcm_files:
        print(f"       - {f.name}")

    pyproject = lcm_types_dir / "pyproject.toml"
    if not pyproject.exists():
        print(f"[ERROR] pyproject.toml not found: {pyproject}")
        sys.exit(1)
    print(f"[INFO] Found pyproject.toml: {pyproject}")

    lcm_gen_path = shutil.which("lcm-gen")
    if lcm_gen_path is None:
        print(
            "[ERROR] lcm-gen not found, please install LCM and ensure lcm-gen is in PATH."
        )
        sys.exit(1)
    print(f"[INFO] Found lcm-gen: {lcm_gen_path}")

    return lcm_types_dir


def generate_python_with_lcm_gen(lcm_types_dir: Path) -> Path:
    """Generate Python files from LCM definitions using the lcm-gen tool."""
    lcm_files = list(lcm_types_dir.glob("*.lcm"))
    assert lcm_files

    lcm_msgs_dir = lcm_types_dir / "lcm_msgs"
    if lcm_msgs_dir.exists():
        print(f"[INFO] Deleting old generated directory: {lcm_msgs_dir}")
        shutil.rmtree(lcm_msgs_dir)

    print(f"[INFO] Generating Python code using lcm-gen (cwd={lcm_types_dir}) ...")
    if sys.platform == "win32":
        cmd = ["lcm-gen.exe", "-p", *[f.name for f in lcm_files]]
    else:
        cmd = ["lcm-gen", "-p", *[f.name for f in lcm_files]]
    run(cmd, cwd=str(lcm_types_dir))

    if not lcm_msgs_dir.is_dir():
        print(
            f"[ERROR] Generated directory not found after lcm-gen execution: {lcm_msgs_dir}"
        )
        sys.exit(1)

    py_files = list(lcm_msgs_dir.glob("*.py"))
    if not py_files:
        print(f"[ERROR] No .py files found in {lcm_msgs_dir}")
        sys.exit(1)

    print("[INFO] Python files generated by lcm-gen:")
    for py in py_files:
        print(f"       - {py.name}")

    return lcm_msgs_dir


def build_pkg_structure_from_lcm_msgs(lcm_msgs_dir: Path) -> None:
    """Reorganize the generated Python files into a proper package structure."""
    pkg_msg_dir = lcm_msgs_dir / "msg"
    if pkg_msg_dir.exists():
        shutil.rmtree(pkg_msg_dir)
    pkg_msg_dir.mkdir(parents=True)

    module_names: list[str] = []
    for py in list(lcm_msgs_dir.glob("*.py")):
        if py.name == "__init__.py":
            continue
        target = pkg_msg_dir / py.name
        print(f"[INFO] Move {py} -> {target}")
        shutil.move(str(py), str(target))
        module_names.append(py.stem)

    pkg_root_init = lcm_msgs_dir / "__init__.py"
    pkg_root_init.write_text(
        "# LCM-based message package\n",
        encoding="utf-8",
    )
    print(f"[INFO] Writing top-level __init__.py: {pkg_root_init}")

    lines: list[str] = [
        '"""Export LCM generated message classes"""',
        "",
    ]
    all_names: list[str] = []
    for mod in sorted(set(module_names)):
        cls_name = mod
        lines.append(f"from .{mod} import {cls_name}")
        all_names.append(cls_name)

    lines.append("")
    lines.append("__all__ = [")
    for name in all_names:
        lines.append(f'    "{name}",')
    lines.append("]")
    lines.append("")

    pkg_msg_init = pkg_msg_dir / "__init__.py"
    pkg_msg_init.write_text("\n".join(lines), encoding="utf-8")
    print(f"[INFO] Writing msg/__init__.py: {pkg_msg_init}")

    print("\n[INFO] Package structure reorganization completed:")
    print(f"    {lcm_msgs_dir}/")
    print(f"        __init__.py")
    print(f"        msg/")
    print(f"            __init__.py")
    print(f"            [Each message *.py file]")


def build_and_install_wheel(lcm_types_dir: Path) -> Path:
    """Build a wheel package and install it using pip."""
    dist_dir = lcm_types_dir / "dist"
    if dist_dir.exists():
        shutil.rmtree(dist_dir)

    print("[INFO] Building wheel package (python -m build --wheel) ...")
    try:
        import build  # noqa: F401
    except ImportError:
        print("[INFO] build not installed, installing build ...")
        run([sys.executable, "-m", "pip", "install", "build"])

    run(
        [sys.executable, "-m", "build", "--wheel", "--outdir", "dist"],
        cwd=str(lcm_types_dir),
    )

    wheels = list(dist_dir.glob("*.whl"))
    if not wheels:
        raise RuntimeError(f"No wheel files found in {dist_dir} after build")

    wheel_path = max(wheels, key=lambda p: p.stat().st_mtime)
    print(f"[INFO] Built wheel: {wheel_path.name}")

    print("[INFO] Installing wheel with pip (--force-reinstall) ...")
    run(
        [sys.executable, "-m", "pip", "install", "--force-reinstall", str(wheel_path)],
        cwd=str(lcm_types_dir),
    )

    return wheel_path


def simple_import_test():
    """Test importing the generated LCM messages to verify successful generation."""
    print("[INFO] Performing simple import test ...")
    try:
        from lcm_msgs import msg  # noqa: F401
        from lcm_msgs.msg import (
            Image,
            CompressedImage,
            Header,
            JointState,
            JointTrajectory,
        )
    except Exception as e:
        print(f"[WARN] Import test failed: {e}")
        print("       Please try manually in Python:")
        print(
            "           from lcm_msgs.msg import Image, CompressedImage, Header, JointState, JointTrajectory"
        )
    else:
        print("[INFO] Import test successful: lcm_msgs.msg.* can be used")


def main():
    """Main function to orchestrate the LCM message generation and installation process."""
    lcm_types_dir = basic_checks()
    lcm_msgs_dir = generate_python_with_lcm_gen(lcm_types_dir)
    build_pkg_structure_from_lcm_msgs(lcm_msgs_dir)
    build_and_install_wheel(lcm_types_dir)

    print("\n[INFO] Done. You can now use in Python:")
    print("    python3 -c 'from lcm_msgs.msg import Image, CompressedImage, Header'")
    print("If there are changes to .lcm, rerun python scripts/gen_lcm.py.")

    simple_import_test()


if __name__ == "__main__":
    main()
