logging:
  log_dir: ~/RynnRcplog/robotMotion
  log_file: robotMotion.log
signal:
  chunk_size: 20
  signal_home_position: [0.0, 0, 0, -1.57079, 0, 1.57079, -0.7853, 0.5]
  block_time: 0.0
  signal_type: "sin"
  signal_amplitude: 0.2
  signal_frequency: 0.1
  random_seed: 5
  random_ratio: 0.0
robot:
  topic_name: "franka_joint_cmd"
  inference_rate: 30.0
  timeout_seconds: 30.0
  joint_names: [ fr3_joint1, fr3_joint2, fr3_joint3, fr3_joint4, fr3_joint5, fr3_joint6, fr3_joint7, gripper ]
  joint_limit_lower: [ -2.7437, -1.5837, -2.9007, -2.8421, -2.8065, 0.8445, -3.0159, 0.0 ]
  joint_limit_upper: [ 2.7437 ,  1.5837,  2.9007, -0.5518,  2.8065, 4.2169,  3.0159, 255.0 ]
  joint_vel_limit: [ 6.28, 6.28, 6.28, 6.28, 6.28, 6.28, 6.28, 1000.0 ]
  joint_acc_limit: [ 62.8, 62.8, 62.8, 62.8, 62.8, 62.8, 62.8, 10000.0 ]
  joint_jerk_limit: [ 6280.0, 6280.0, 6280.0, 6280.0, 6280.0, 6280.0, 6280.0, 1000000.0 ]
  vel_limit_ratio: 0.05
simulation:
  scene_path: {1: "models/franka/franka_fr3/scene/scene.xml"}
plot:
  enable_joint_plotting: false
  enable_interpolator_plotting: false
  show_plots: false
