"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class camera_ctrl_response(object):

    __slots__ = ["seq", "stamp", "id", "response", "response_msg"]

    __typenames__ = ["int32_t", "int64_t", "int32_t", "int32_t", "string"]

    __dimensions__ = [None, None, None, None, None]

    def __init__(self):
        self.seq = 0
        """ LCM Type: int32_t """
        self.stamp = 0
        """
        Sequence number
        LCM Type: int64_t
        """

        self.id = 0
        """
        Timestamp in nanoseconds (ROS2 style)
        LCM Type: int32_t
        """

        self.response = 0
        """ LCM Type: int32_t """
        self.response_msg = ""
        """ LCM Type: string """

    def encode(self):
        buf = BytesIO()
        buf.write(camera_ctrl_response._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">iqii", self.seq, self.stamp, self.id, self.response))
        __response_msg_encoded = self.response_msg.encode('utf-8')
        buf.write(struct.pack('>I', len(__response_msg_encoded)+1))
        buf.write(__response_msg_encoded)
        buf.write(b"\0")

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != camera_ctrl_response._get_packed_fingerprint():
            raise ValueError("Decode error")
        return camera_ctrl_response._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = camera_ctrl_response()
        self.seq, self.stamp, self.id, self.response = struct.unpack(">iqii", buf.read(20))
        __response_msg_len = struct.unpack('>I', buf.read(4))[0]
        self.response_msg = buf.read(__response_msg_len)[:-1].decode('utf-8', 'replace')
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if camera_ctrl_response in parents: return 0
        tmphash = (0xe8324ab9a210e8c2) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if camera_ctrl_response._packed_fingerprint is None:
            camera_ctrl_response._packed_fingerprint = struct.pack(">Q", camera_ctrl_response._get_hash_recursive([]))
        return camera_ctrl_response._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", camera_ctrl_response._get_packed_fingerprint())[0]

