"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class camera_desc(object):

    __slots__ = ["id", "product", "name", "fps", "width", "height", "format", "status"]

    __typenames__ = ["int32_t", "string", "string", "int32_t", "int32_t", "int32_t", "string", "int32_t"]

    __dimensions__ = [None, None, None, None, None, None, None, None]

    def __init__(self):
        self.id = 0
        """ LCM Type: int32_t """
        self.product = ""
        """ LCM Type: string """
        self.name = ""
        """ LCM Type: string """
        self.fps = 0
        """ LCM Type: int32_t """
        self.width = 0
        """ LCM Type: int32_t """
        self.height = 0
        """ LCM Type: int32_t """
        self.format = ""
        """ LCM Type: string """
        self.status = 0
        """
        image format, ex: YUV, jpeg.
        LCM Type: int32_t
        """


    def encode(self):
        buf = BytesIO()
        buf.write(camera_desc._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">i", self.id))
        __product_encoded = self.product.encode('utf-8')
        buf.write(struct.pack('>I', len(__product_encoded)+1))
        buf.write(__product_encoded)
        buf.write(b"\0")
        __name_encoded = self.name.encode('utf-8')
        buf.write(struct.pack('>I', len(__name_encoded)+1))
        buf.write(__name_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">iii", self.fps, self.width, self.height))
        __format_encoded = self.format.encode('utf-8')
        buf.write(struct.pack('>I', len(__format_encoded)+1))
        buf.write(__format_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">i", self.status))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != camera_desc._get_packed_fingerprint():
            raise ValueError("Decode error")
        return camera_desc._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = camera_desc()
        self.id = struct.unpack(">i", buf.read(4))[0]
        __product_len = struct.unpack('>I', buf.read(4))[0]
        self.product = buf.read(__product_len)[:-1].decode('utf-8', 'replace')
        __name_len = struct.unpack('>I', buf.read(4))[0]
        self.name = buf.read(__name_len)[:-1].decode('utf-8', 'replace')
        self.fps, self.width, self.height = struct.unpack(">iii", buf.read(12))
        __format_len = struct.unpack('>I', buf.read(4))[0]
        self.format = buf.read(__format_len)[:-1].decode('utf-8', 'replace')
        self.status = struct.unpack(">i", buf.read(4))[0]
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if camera_desc in parents: return 0
        tmphash = (0x2dd42a0515c0a7d8) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if camera_desc._packed_fingerprint is None:
            camera_desc._packed_fingerprint = struct.pack(">Q", camera_desc._get_hash_recursive([]))
        return camera_desc._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", camera_desc._get_packed_fingerprint())[0]

