# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: RobotServerTransportPacket.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'RobotServerTransportPacket.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n RobotServerTransportPacket.proto\x12\x0bRobotServer\"=\n\x0e\x43ommonPartAttr\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\n\n\x02id\x18\x02 \x01(\x05\x12\x0c\n\x04type\x18\x03 \x01(\x05\"Q\n\nDataPacket\x12\x35\n\x10\x63ommon_part_attr\x18\x01 \x01(\x0b\x32\x1b.RobotServer.CommonPartAttr\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c*y\n\x0bPackageType\x12\x08\n\x04RESV\x10\x00\x12\x0e\n\nIMAGE_DATA\x10\x01\x12\x0e\n\nSTATE_DATA\x10\x02\x12\x0f\n\x0b\x41\x43TION_DATA\x10\x03\x12\r\n\tREQ_IMAGE\x10\x04\x12\r\n\tREQ_STATE\x10\x05\x12\x11\n\rACTION_FINISH\x10\x06\x42$\n com.alibaba.damo.robot.transportP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RobotServerTransportPacket_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n com.alibaba.damo.robot.transportP\001'
  _globals['_PACKAGETYPE']._serialized_start=195
  _globals['_PACKAGETYPE']._serialized_end=316
  _globals['_COMMONPARTATTR']._serialized_start=49
  _globals['_COMMONPARTATTR']._serialized_end=110
  _globals['_DATAPACKET']._serialized_start=112
  _globals['_DATAPACKET']._serialized_end=193
# @@protoc_insertion_point(module_scope)
